services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app.app
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - FLASK_ENV=production
    depends_on:
      db:
        condition: service_healthy
    command: ["./wait-for-postgres.sh", "db", "5432", "--", "gunicorn", "-b", "0.0.0.0:5000", "app.app:app"]
    volumes:
      - uploads:/uploads

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d talent_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
  uploads: