name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: talent_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install project dependencies
      working-directory: ./config
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt psycopg2-binary

    - name: Install system dependencies
      run: sudo apt-get install -y libpq-dev python3-dev

    - name: Setup environment variables
      run: |
        echo "FLASK_APP=app.app" >> $GITHUB_ENV
        echo "DATABASE_URL=postgresql://user:password@localhost:5432/talent_db" >> $GITHUB_ENV

    - name: Debug database connection
      run: |
        psql -h localhost -U user -d talent_db -c "\dt"
      env:
        PGPASSWORD: password

    - name: Run tests
      env:
        DATABASE_URL: postgresql://user:password@localhost:5432/talent_db
      run: pytest test_api.py -v --cov=app --cov-report=xml
