name: Tests  # Nome do workflow

on:  # Eventos que disparam a execução
  push:  # Executa a cada push
    branches: [ main ]
  pull_request:  # Executa a cada pull request
    branches: [ main ]

jobs:
  test:  # Nome do job
    runs-on: ubuntu-latest  # Sistema operacional do runner

    services:  # Adicionar serviço PostgreSQL
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: talent_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    # Passo 1: Baixar o código do repositório
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('config/requirements.txt') }}

    - name: Install system dependencies
      run: sudo apt-get install -y libpq-dev python3-dev

    # Passo 3: Instalar dependências
    - name: Install dependencies
      working-directory: ./config
      run: pip install -r requirements.txt

    # Passo 4: Executar testes
    - name: Run tests
      env:
        DATABASE_URL: postgresql://user:password@localhost:5432/talent_db
      run: pytest test_api.py -v  # O "-v" mostra detalhes
